# Generated by Django 4.2.2 on 2023-06-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='repuesto',
            fields=[
                ('id_rep', models.AutoField(db_column='respuesto', primary_key=True, serialize=False)),
                ('tipo_repuesto', models.CharField(max_length=20)),
                ('stock_rep', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(db_column='vehiculo', primary_key=True, serialize=False)),
                ('modelo_vehiculo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('rut', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='mecanico',
            fields=[
                ('id_mecanico', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_mec', models.CharField(max_length=20)),
                ('apellido_mec', models.CharField(max_length=20)),
                ('tele', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_vehiculo', models.ForeignKey(db_column='vehiculo', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='mantencion_repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_mantencion', models.CharField(max_length=300)),
                ('fecha_mantencion', models.DateField()),
                ('id_mecanico', models.ForeignKey(db_column='mecanico', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.mecanico')),
                ('id_rep', models.ForeignKey(db_column='repuesto', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.repuesto')),
                ('id_vehiculo', models.ForeignKey(db_column='vehiculo', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.vehiculo')),
                ('rut', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_mantencion', models.CharField(max_length=300)),
                ('fecha_mantencion', models.DateField()),
                ('id_mecanico', models.ForeignKey(db_column='mecanico', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.mecanico')),
                ('id_vehiculo', models.ForeignKey(db_column='vehiculo', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.vehiculo')),
                ('rut', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.CASCADE, to='tlmecanic.cliente')),
            ],
        ),
    ]
